dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=live setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: lDNDBzNiGCvUp/iHK2qStiOt2o2e5MGy3oTfYE7Jbx3IPxQ+R5FroeKvXHWU8itv395IJDYUVRY2hnzTS2bOYlYOSV5gfpAZdfFc+kxTYehiT4M5WCHlfWqHTt4YpnmhCXaeW+MX7v+L9V46apyK+LA7kO/oRdkWZLooZdmQV9o=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
