sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=live setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: lDNDBzNiGCvUp/iHK2qStiOt2o2e5MGy3oTfYE7Jbx3IPxQ+R5FroeKvXHWU8itv395IJDYUVRY2hnzTS2bOYlYOSV5gfpAZdfFc+kxTYehiT4M5WCHlfWqHTt4YpnmhCXaeW+MX7v+L9V46apyK+LA7kO/oRdkWZLooZdmQV9o=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
